#!/usr/bin/env bash
# Compose a buildable config from a board and a variant.
#
#   ./compose.sh <board> <variant> > _build.yaml
#
# Kept as a script rather than 28 committed files: board x variant is a product,
# and writing it out by hand means a change to one board has to be repeated in
# every variant of it. CI calls this; so can you, to reproduce a build locally.
#
# Main-config keys beat package keys in ESPHome, so the variant's
# bluetooth_proxy: block overrides whatever config/adopt/<board>.yaml set.
set -euo pipefail
board="${1:?usage: compose.sh <board> <variant>}"
variant="${2:?usage: compose.sh <board> <variant>}"
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

[[ -f "$here/$board.yaml" ]]            || { echo "no such board: $board" >&2; exit 1; }
[[ -f "$here/variants/$variant.yaml" ]] || { echo "no such variant: $variant" >&2; exit 1; }

cat <<EOF
# GENERATED by firmware/compose.sh — do not edit.
# board: $board   variant: $variant

packages:
  board: !include $board.yaml

EOF
cat "$here/variants/$variant.yaml"
